name: first workflow

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: |
          echo "hi"
          echo "nada"
      - name: bye
        run: echo "bye"
